print("Welcome to the tip calculator")
bill=input("What was the total bill amount? ")
percentage=input("What percentage tip would you like to give? 10, 12 or 15? ")
people=input("How many people to split the bill? ")
print(f"Each person should pay ₹{(int(bill)*int(percentage))/(100*float(people))}")