name="Faran Mohammad lives in Gorakhpur"
print(name)
print(len(name))
print(name.capitalize())
print(name.casefold())
print(name.center(5)
#print(name.count())
print(name.encode(encoding="ascii",errors="backslashreplace"))
print(name.endswith())
print(name.expandtabs())
print(name.find('m'))
print(name.format())
print(name.isalnum())
print(name.isalpha())
print()